//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academic_Records_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Telephne { get; set; }
        public string Address { get; set; }
        public string Major { get; set; }
        public string ClassNumber { get; set; }
        public System.DateTime EnrolDate { get; set; }
        public Nullable<System.DateTime> GraduateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    }
}
